### ISSUE TITLE
Offset in index parameters between xxxHql and xxxLinq intended?

### ISSUE THREAD

**Issue by FObermaier** [nhibernate/NHibernate.Spatial#5]
I'm working on adding SpatiaLite support for NHibernate. In the process of getting the unit tests to pass, I noticed that there is an offset in the argument indices between the Hql and Linq test functions. Is that intended?

The tests
- ConformanceItemT23Linq
- ConformanceItemT29Linq
- ConformanceItemT31Linq
only pass for spatialite, if I adjust the indices to those of the Hql counterparts.

**Comment by andrerav** [comment]
Some functions, like PointN and InteriorRingN are zeroindexed in some databases and 1-indexed in others. To make the tests conform to how SpatialLite treats these functions, simply override them in the test project. How did it go otherwise with this dialect? I would love to see this realized, so I'd be happy to help out :)

**Comment by peetw** [comment]
I'm currently using a modified version of @FObermaier 's SpatiaLite project with good success in our current project. It's been a while since I got it set up, but I can try and fork the repo and apply my changes and see how it fares with the NHibernate.Spatial tests :)

**Comment by andrerav** [comment]
That would be great. Would it be easier for you if I pull from @FObermaier
to a new branch which you can fork?

-Andreas

**Comment by peetw** [comment]
Sounds good

**Comment by andrerav** [comment]
I'll close this issue now and open a new one.
