### ISSUE TITLE
MsSql2012SpatialDialect does not inherit MsSql2012Dialect

### ISSUE THREAD

**Issue by jeffreyabecker** [nhibernate/NHibernate.Spatial#70]
This makes new features of MsSql2012 such as sequences, limit and iff unavailable when using a geometry type

**Comment by peetw** [comment]
Hi, apologies for not replying to your google group post a while back - MS SQL is not something I have much knowledge of or access to, sorry!

However, it looks like this shouldn't be a particularly difficult fix (just change `MsSql2012SpatialDialect` to inherit from `MsSql2012Dialect`, rather than `MsSql2008SpatialDialect`. Then implement the new 2012 features (the hard part?).

I don't _think_  a new `MsSql2012GeometryType` will be required (unless the implementation has changed between 2008 and 2012?).

Any help would be greatly appreciated :)

**Comment by jeffreyabecker** [comment]
You're correct about the simplicity of this.  I'll get a pull request worked up.

**Comment by peetw** [comment]
Perfect, thanks!

**Comment by jeffreyabecker** [comment]
should I base it on a particular branch?

**Comment by andrerav** [comment]
master is good, we don't have a particular development branch at this time.
If you submit a pull request I will check the status of the tests on the
build server and give you feedback if necessary.

**Comment by peetw** [comment]
New developments should branch off of the `master` branch (don't forget to include the issue number in the branch name, i.e. 'ms-ql-2012-#70')

**Comment by jeffreyabecker** [comment]
So I've got stuff written but I cant get the mssql tests to successfully run on my local machine. Is there any specific setup I need to do?

**Comment by peetw** [comment]
You'll need to create a new user and database on a local MS SQL server. The tests tend to use `nhsp_test` for both the username and database name, but you can check the connection string in the [app.config](https://github.com/nhibernate/NHibernate.Spatial/blob/master/Tests.NHibernate.Spatial.MsSql2008/app.config#L9) file.

You'll also need to create a new `Tests.NHibernate.Spatial.MsSql2012` test project.

I also assume that you've tested it locally using the new 2012 features (e.g. sequences, limit, iff, etc)?

**Comment by jeffreyabecker** [comment]
Hrm...
I did create the database and associated users and all that but I'm still getting failing tests.  Something about shared memory not being available.  I'll dig into it further
I'm considering rewriting my unit tests for better coverage.

**Comment by peetw** [comment]
So I ended up installing MS SQL 2012 locally, and it turns out that in order to run the tests, you need to make sure that your local server accepts logins using both Windows and SQL Server authentication methods (see [here](https://stackoverflow.com/a/23395581/3628232) for instructions). Otherwise you will get the error message that you observed (viewing the MS SQL Server logs themselves made it easier to debug).

**Comment by jeffreyabecker** [comment]
Oh, yeah. My sql server probably has sql logins turned off.

**Comment by peetw** [comment]
@jeffreyabecker how are you getting on? I've got some more time available now, so if you've got some tests for the new 2012 features that you could share (e.g. sequences, limit, iff, etc), I can have a go at getting it all implemented and ready for you if you don't have the time at the moment :)

**Comment by peetw** [comment]
@andrerav @suryapratap somewhat related - is the `Tests.NHibernate.Spatial.MsSqlSpatial` test project intended to be for testing the `MsSql2012SpatialDialect`? It currently appears that way since it uses the `MsSql2012GeometryDialect` as the Dialect property in the test configuration. Or is it for something else?

**Comment by jeffreyabecker** [comment]
I've been slammed with other work honestly.  I had been intending on separating the test suites for 2008/2012. My code basically copy-pastes an existing class so it should get its own test suite.  If you want to take a look at what I did, I've got a branch in my repository which you can look at.  The implementation of the sql2012 stuff itself is pretty darn trivial as all the functionality is implemented in the base dialect inherited from NHibernate core.

**Comment by peetw** [comment]
@jeffreyabecker no worries, it just so happens that I actually have some "spare" time at work for once :) Yes, the implementation is pretty easy. However, what would be great, would be a very minimal example using some of the features that are only available in the MsSql2012 dialect (and that fail when using the MsSql2008 dialect) - I assume you have something already that was the reason you posted the issue in the first place? Or is that example part of code that you can't share (proprietary, etc)?

**Comment by jeffreyabecker** [comment]
The easiest thing I can think of is to have an entity with a sequence hi/lo id generator.  There's a test-case in my repository which covers this already.

**Comment by peetw** [comment]
Ah yes, sorry I didn't see the new test fixture - thanks!
