### ISSUE TITLE
Unable to save the geography in PostGIS

### ISSUE THREAD

**Issue by KapecK** [nhibernate/NHibernate.Spatial#8]
When I try to save the geography: 
"Column "adr_geography" is a type of geography but expression is of type text"

ErrorSQL:
UPDATE dbo.adres SET ADR_GEOGRAPHY = ((E'0101000020000000000000000000004E400000000000003440')::text) WHERE ADR_ID = ((34)::int4)

Code:
 address[0].Geography = new Point(60,20);
 transaction.Commit();

**Comment by andrerav** [comment]
@KapecK Did you figure out this problem? If not, can you please provide your code/mapping?

**Comment by andrerav** [comment]
I think this might be related:
1. https://nhibernate.jira.com/browse/NHSP-15
2. http://stackoverflow.com/questions/24630689/npgsql-to-postgis-adds-text-making-st-intersects-fail/24634084#24634084

**Comment by sugarp** [comment]
Hi,

Have you solved the issue? Im facing the same thing, without any success.

**Comment by peetw** [comment]
@sugarp do you have a simple example that reproduces the issue? If so I can try and have a look for you :)

**Comment by sugarp** [comment]
Hi,

Wow, thanks for the will man. 

I tried to simplify my solution, but let me know if you want me to create really minimal solution. 
It uses FluentNHibernate and SharpArchNHibernate for initialization. I also tried to use only FluentNhibernate classed to initialize nHibernate, but error was the same. 
I used to use MicrosoftSQL where domain, mapping, conventions and so on worked just fine as it is. 
I established public database instance, which is already configured in repo. There is PostgreSQL 9.6 with PostGIS 2.3.1. 

https://github.com/sugarp/PostGISTest

It is WebAPI project, so I put code causing error into global.asax.cs into Application_BeginRequest function. Further, explore the solution for these classes:
-NHibernateHelper.cs
-FeaturesList.cs
-FeaturesListMap.cs for fluent mapping override ("geometry type defined")
-Wgs84GeographyType.cs which is the type inheritting from GeometryType class 
                                           and other conventions is same namespace

I use AutoPersistenceModel so there is also:
-AutoPersistenceModelGenerator
-AutomappingConfiguration

**Comment by peetw** [comment]
@sugarp sorry for the delayed response! I've had a quick look, but I wasn't able to work out exactly what mappings you were using? It appears as if you are not actually correctly mapping any of your entities... If you could post a MWE (minimal working example) that replicates the issue, I can take a look :) Otherwise, I will close the issue.

**Comment by sugarp** [comment]
Hi,Thank you for reaching me. Anyway i already found the issue and fixed it. My mapping was using incorrect dialect specific spatial type.Please close it.Thank you,PetrOn Jun 19, 2017 12:22 PM, Peet Whittaker <notifications@github.com> wrote:@sugarp sorry for the delayed response! I've had a quick look, but I wasn't able to work out exactly what mappings you were using? It appears as if you are not actually correctly mapping any of your entities... If you could post a MWE (minimal working example) that replicates the issue, I can take a look :) Otherwise, I will close the issue.

**Comment by peetw** [comment]
@sugarp ok, thanks for the update - glad you managed to get it working!
